CREATE TABLE USER_PROFILE (
  USER_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(20) NOT NULL,
  LAST_NAME varchar(20) NOT NULL,
  EMAIL_ID varchar(30) NOT NULL,
  PHONE_NUMBER int(13) NOT NULL,
  GENDER varchar(20) NOT NULL,
  USER_ROLE varchar (15) NOT NULL,
  USER_ACTIVE_STATUS int(1) NOT NULL,
  PASSWORD varchar(100) NOT NULL,
  CREATED_DTTM datetime NOT NULL,
  MODIFIED_DTTM datetime NULL,
  MODIFIED_BY varchar(20) NULL,
  PRIMARY KEY (USER_ID)
  UNIQUE (EMAIL_ID)
);

CREATE TABLE BLOG(
	BLOG_ID int(11) NOT NULL AUTO_INCREMENT,
	TITLE varchar(50) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
        HASH_TAG varchar(200) NULL,
	IMAGE_PATH varchar(100) NULL,
	USER_ID int NOT NULL,
        CREATED_DTTM DATETIME NOT NULL,
        MODIFIED_DTTM DATETIME NOT NULL,
	PRIMARY KEY (BLOG_ID),
    	FOREIGN KEY (USER_ID) REFERENCES USER_PROFILE(USER_ID)
);